resources:
  - deployment.yaml
  - vault-secret.yaml

namespace: default

labels:
  - pairs:
      app.kubernetes.io/part-of: home-automation
      app.kubernetes.io/name: tapo
    includeSelectors: true

images:
  - name: ghcr.io/mihai-dinculescu-lab/home-automation-tapo
    newTag: "main"
